"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var service_1 = require("./engine/service");
var service_2 = require("./agent/service");
var app_1 = require("./admin/service/app");
var process = require("process");
var _a = process.argv.slice(2), portSocket = _a[0], portApi = _a[1];
var socketserver = "ws://localhost:" + portSocket;
var dirname = process.cwd();
var config = require('nodeci.config.js');
service_1.start(+portSocket, config);
service_2.start(socketserver, 'self-hosted', dirname);
app_1.start(+portApi, socketserver);
